version: '3.7'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  service-user:
    container_name: service-user
    build:
      context: ./service-user
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db-user
    networks:
      - mynetwork

  service-employee:
    container_name: service-employee
    build:
      context: ./service-employee
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db-employee
    networks:
      - mynetwork

  db-user:
    image: postgres:13
    container_name: db-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - user-db-data:/var/lib/postgresql/data

  db-employee:
    image: postgres:13
    container_name: db-employee
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - mynetwork
    volumes:
      - employee-db-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  user-db-data:
  employee-db-data:
